# Check new version.
versionCheck: true

defaultBalance: 10000.0
createAccountOnJoin: true

format:
    singularMajorSingularMinor: "{major} dollar {minor} cent"
    singularMajorPluralMinor: "{major} dollar {minor} cents"
    pluralMajorSingularMinor: "{major} dollars {minor} cent"
    pluralMajorPluralMinor: "{major} dollars {minor} cents"
    singleMajorZeroMinor: "{major} dollar"
    pluralMajorZeroMinor: "{major} dollars"

database:
    # Database type. (sqlite/mysql)
    type: sqlite
    sqlite:
        file: "jecon.db"
    mysql:
        host: "localhost:3306"
        name: "jecon"
        username: "root"
        password: "your_mysql_password"
        # It is recommended to stop caching when using MySQL
        # If you have caches in your application, database cache is "wasted memory".
        init: "SET SESSION query_cache_type=0"
        properties:
            "useSSL": "false"
            # encoding
            #"useUnicode": "true"
            #"characterEncoding": "UTF-8"
            #"characterSetResults": "UTF-8"
            # performance
            "maintainTimeStats": "false"
            "elideSetAutoCommits": "true"
            "useLocalSessionState": "true"
            "alwaysSendSetIsolation": "false"
            "cacheServerConfiguration": "true"
            "cachePrepStmts": "true"
            "prepStmtCacheSize": "250"
            "prepStmtCacheSqlLimit": "2048"
            #"useServerPrepStmts": "true"
    connectionPool:
        # -1 is default
        maximumPoolSize: -1
        minimumIdle: -1
        maxLifetime: -1
        connectionTimeout: -1
        idleTimeout: -1

cache:
    # +n == The specified number is stored in the LRU cache(memory saving)
    # -1 == Infinity(fast)
    #  0 == Disable(When using from multiple servers)
    id: -1
    balance: -1

# Don't touch
version: 3
