# 新しいバージョンを確認します。
versionCheck: true

defaultBalance: 10000.0
createAccountOnJoin: true

#lazyWriteはデータベースの書き込みを減らし、パフォーマンスを向上させます。
#ただし、データベースを共有する複数のサーバー（BungeeCordなど）がある場合、プレーヤーのバランスが一時的に不正確になる可能性があります。
#キャッシュコヒーレンシアルゴリズムは、バランスが最終的に正しいことを保証します。
#プレーヤーのバランスを常に正確に保つ必要がある場合は、この機能を無効にしてください。
lazyWrite: true

format:
  singularMajor: "dollar"
  pluralMajor: "dollars"
  singularMinor: "cent"
  pluralMinor: "cents"
  format: "{major} {majorcurrency} {minor} {minorcurrency}"
  #オプション
  #formatZeroMinor： "{major} {majorcurrency}"
  #例：
  #format： "$ {メジャー}。{マイナー}"
  #format： "{major}円"

database:
  # Database type. (sqlite/mysql)
  type: sqlite
  sqlite:
    file: "jecon.db"
  mysql:
    host: "localhost:3306"
    name: "jecon"
    username: "root"
    password: "your_mysql_password"
    #MySQLを使用する場合は、キャッシュを停止することをお勧めします
    #アプリケーションにキャッシュがある場合、データベースキャッシュは「無駄なメモリ」です。
    init: "SET SESSION query_cache_type=0"
    properties:
      "useSSL": "false"
      # エンコーディング
      # "useUnicode"： "true"
      # "characterEncoding"： "UTF-8"
      # "characterSetResults"： "UTF-8"
      # パフォーマンス
      "maintainTimeStats": "false"
      "elideSetAutoCommits": "true"
      "useLocalSessionState": "true"
      "alwaysSendSetIsolation": "false"
      "cacheServerConfiguration": "true"
      "cachePrepStmts": "true"
      "prepStmtCacheSize": "250"
      "prepStmtCacheSqlLimit": "2048"
      # "useServerPrepStmts"： "true"
  connectionPool:
    #-1がデフォルトです
    maximumPoolSize: -1
    minimumIdle: -1
    maxLifetime: -1
    connectionTimeout: -1
    idleTimeout: -1

# 触れないでください
version: 3
