main: "jp.jyn.jecon.Jecon"
name: "Jecon"
version: "${project.version}"
website: "${project.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "Jecon is a simple economy plugin."
load: STARTUP
loadbefore: [Vault]

commands:
    jecon:
        description: "'/jecon help' - Show helps."
        aliases: money

permissions:
    jecon.*:
        children:
            jecon.show: true
            jecon.pay: true
            jecon.show.other: true
            jecon.give: true
            jecon.take: true
            jecon.set: true
            jecon.create: true
            jecon.remove: true
            jecon.top: true
            jecon.reload: true
    jecon.user:
        children:
            jecon.show: true
            jecon.pay: true
    jecon.op:
        children:
            jecon.show.other: true
            jecon.give: true
            jecon.take: true
            jecon.set: true
            jecon.create: true
            jecon.remove: true
            jecon.top: true
            jecon.reload: true
    jecon.show:
        default: true
    jecon.pay:
        default: true
    jecon.show.other:
        default: op
    jecon.give:
        default: op
    jecon.take:
        default: op
    jecon.set:
        default: op
    jecon.create:
        default: op
    jecon.remove:
        default: op
    jecon.top:
        default: op
    jecon.reload:
        default: op
